# Generated by Django 2.0.13 on 2019-02-28 17:54

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_types', models.CharField(choices=[('star', 'Startup'), ('sh', 'Software House'), ('ecom', 'E-commerce'), ('corp', 'Corporation')], max_length=4)),
                ('company_workers', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('company_headquarters', models.CharField(max_length=100)),
                ('company_technologies', multiselectfield.db.fields.MultiSelectField(choices=[('php', 'PHP'), ('js', 'JavaScript'), ('ang', 'Angular'), ('java', 'Java'), ('ruby', 'Ruby'), ('ror', 'Ruby on Rails'), ('jee', 'Java EE'), ('python', 'Python'), ('django', 'Django')], max_length=25)),
                ('company_about', models.TextField(max_length=500)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
