# Generated by Django 2.0.13 on 2019-03-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_headquarters',
            new_name='city',
        ),
    ]
