# Generated by Django 2.0.13 on 2019-03-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190301_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_technologies',
            new_name='stack',
        ),
    ]
