# Generated by Django 2.0.13 on 2019-03-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20190301_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_types',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_workers',
            new_name='workers',
        ),
    ]
