# Generated by Django 2.0.13 on 2019-03-22 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190322_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_type',
            name='type',
            field=models.CharField(choices=[('B2B', 'B2B'), ('Umowa o prace', 'Umowa o prace'), ('Umowa zlecenie', 'Umowa zlecenie'), ('Umowa o dzielo', 'Umowa o dzielo'), ('Staz', 'Staz'), ('Praktyki', 'Praktyki')], max_length=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
    ]
