# Generated by Django 2.0.13 on 2019-03-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20190302_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='stack',
            field=models.CharField(choices=[('php', 'PHP'), ('js', 'JavaScript'), ('ang', 'Angular'), ('java', 'Java'), ('ruby', 'Ruby'), ('ror', 'Ruby on Rails'), ('jee', 'Java EE'), ('python', 'Python'), ('django', 'Django')], max_length=25),
        ),
    ]
