# Generated by Django 2.0.13 on 2019-03-05 13:21

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20190302_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='students',
            field=models.CharField(choices=[(0, 'No'), (1, 'Yes')], default='value', max_length=1),
        ),
        migrations.AlterField(
            model_name='company',
            name='stack',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PHP', 'PHP'), ('js', 'JavaScript'), ('ang', 'Angular'), ('java', 'Java'), ('ruby', 'Ruby'), ('ror', 'Ruby on Rails'), ('jee', 'Java EE'), ('python', 'Python'), ('django', 'Django')], max_length=42),
        ),
        migrations.AlterField(
            model_name='company',
            name='stack_two',
            field=models.CharField(choices=[('PHP', 'PHP'), ('js', 'JavaScript'), ('ang', 'Angular'), ('java', 'Java'), ('ruby', 'Ruby'), ('ror', 'Ruby on Rails'), ('jee', 'Java EE'), ('python', 'Python'), ('django', 'Django')], default='value', max_length=15),
        ),
    ]
