# Generated by Django 2.0.13 on 2019-03-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20190305_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='value', unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='students',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3),
        ),
    ]
