# Generated by Django 2.0.13 on 2019-03-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_remove_company_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='value'),
            preserve_default=False,
        ),
    ]
