# Generated by Django 2.0.13 on 2019-03-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auto_20190308_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(choices=[('Warszawa', 'Warszawa'), ('Poznan', 'Poznan'), ('Szczecin', 'Szczecin'), ('Gdansk', 'Gdansk'), ('Krakow', 'Krakow'), ('Wroclaw', 'Wroclaw'), ('Katowice', 'Katowice'), ('Gliwice', 'Gliwice')], max_length=15),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('Startup', 'Startup'), ('software_house', 'Software House'), ('e-commerce', 'E-commerce'), ('corporation', 'Corporation')], max_length=15),
        ),
    ]
