# Generated by Django 2.0.13 on 2019-03-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_auto_20190308_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('Startup', 'Startup'), ('Software House', 'Software House'), ('E-commerce', 'E-commerce'), ('Corporation', 'Corporation')], max_length=15),
        ),
    ]
