# Generated by Django 2.0.13 on 2019-03-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20190308_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='icon',
            field=models.CharField(blank=True, choices=[('startup.png', 'Startup'), ('software_house.png', 'Software House'), ('e-commerce.png', 'E-commerce'), ('corporation.png', 'Corporation'), ('other.png', 'Other')], max_length=20, null=True),
        ),
    ]
