# Generated by Django 2.0.13 on 2019-03-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_auto_20190316_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
