# Generated by Django 2.0.13 on 2019-03-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PHP', 'PHP'), ('js', 'JavaScript'), ('ang', 'Angular'), ('java', 'Java'), ('ruby', 'Ruby'), ('ror', 'Ruby on Rails'), ('jee', 'Java EE'), ('python', 'Python'), ('django', 'Django')], max_length=30)),
                ('icon', models.CharField(choices=[('/static/icons/stack/php.png', 'PHP'), ('/static/icons/stack/javascript.png', 'JavaScript')], max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='stack',
        ),
        migrations.RemoveField(
            model_name='company',
            name='stack_two',
        ),
        migrations.AddField(
            model_name='company',
            name='technologies',
            field=models.ManyToManyField(to='company.Stack'),
        ),
    ]
