# Generated by Django 2.0.13 on 2019-03-17 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_auto_20190317_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='facebook',
            field=models.TextField(blank=True, max_length=150, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram',
            field=models.TextField(blank=True, max_length=150, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin',
            field=models.TextField(blank=True, max_length=150, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='company',
            name='twitter',
            field=models.TextField(blank=True, max_length=150, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.TextField(blank=True, max_length=150, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
