# Generated by Django 2.0.13 on 2019-03-18 13:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_auto_20190317_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('about', models.TextField(default=None, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='facebook',
            field=models.TextField(blank=True, max_length=150, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram',
            field=models.TextField(blank=True, max_length=150, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin',
            field=models.TextField(blank=True, max_length=150, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='company',
            name='twitter',
            field=models.TextField(blank=True, max_length=150, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.TextField(blank=True, max_length=150, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='company',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.Person'),
        ),
    ]
