# Generated by Django 2.0.13 on 2019-03-18 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_auto_20190318_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='team',
        ),
    ]
