# Generated by Django 2.0.13 on 2019-03-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_remove_company_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('CEO', 'Chief Executive Officer'), ('CTO', 'Chief Technology Officer'), ('COO', 'Chief Operating Officer'), ('CFO', 'Chief Financial Officer'), ('Co-Founder', 'Co-Founder'), ('Lead Software Developer', 'Lead Software Developer'), ('HR Recruiter', 'HR recruiter')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.ManyToManyField(to='company.Position'),
        ),
    ]
