# Generated by Django 2.0.13 on 2019-03-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_auto_20190318_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.CharField(choices=[('CEO', 'Chief Executive Officer'), ('CTO', 'Chief Technology Officer'), ('COO', 'Chief Operating Officer'), ('CFO', 'Chief Financial Officer'), ('Co-Founder', 'Co-Founder'), ('Lead Software Developer', 'Lead Software Developer'), ('Software Developer', 'Software Developer'), ('Front-end Developer', 'Front-end Developer'), ('Back-end Developer', 'Back-end Developer'), ('QA Engineer', 'QA Engineer'), ('Scrum Master', 'Scrum Master'), ('HR Recruiter', 'HR recruiter')], max_length=50),
        ),
    ]
