# Generated by Django 2.0.13 on 2019-03-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_company_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
