# Generated by Django 2.0.13 on 2019-03-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='team',
            field=models.ManyToManyField(to='company.Person'),
        ),
    ]
